name: Use Custom Action

on:
  workflow_dispatch:

jobs:
  use-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom action
        uses: irivers6119/prr_ghe_action@main
        
        with:
          Default: ${{ github.repository }}
          input_component: 'eventer-event-bridge-proxy'
          input_component_id: 'CI0651176'
        env:
          AUTH: ${{ secrets.AUTH }}